#248 fix date formatting
josdem/vetlog-spring-boot pull request #249
Opened 2023-10-31 20:52 UTC by josdem

Adding PR, so the team can review and approve.

2023-10-31 21:01 UTC, marki2121 requested changes

2023-10-31 21:01 UTC, marki2121 commented on src/test/java/com/jos/dem/vetlog/util/DateFormatterTest.java
> +        // when
Remove comments

2023-11-01 09:42 UTC, marki2121 approved these changes

2023-11-01 11:59 UTC, josdem commented
@marki2121 and @SinyukKirill I like this approach since the code looks cleaner; however, I know we will introduce a bug for users trying to list pets if they are using the Spanish `locale` configuration. Therefore I created this ticket to complement this solution: https://github.com/josdem/vetlog-spring-boot/issues/253

2023-11-01 15:38 UTC, SinyukKirill commented
@josdem here was another possible problem due to changing `formatter` field within the bean. 
All threads use the same bean which lead to resource competition.
It'd be better to get format from properties if we have to change it depends on locale.

2023-11-01 23:07 UTC, closed without merging