pet service changed
josdem/vetlog-spring-boot pull request #324
Opened 2024-09-08 13:02 UTC by yashudhlani

2024-09-08 18:44 UTC, josdem requested changes
@yashudhlani  Overall I like the changes, just little improvements. Great job! 👍

2024-09-08 18:44 UTC, josdem commented on src/main/java/com/josdem/vetlog/service/impl/PetServiceImpl.java
>              throw new BusinessException(NO_USER_WAS_FOUND_WITH_ID + petCommand.getUser());
I suggest using method class reference, since it is cleaner:
`user.ifPresentOrElse(pet::setUser, () -> {`

2024-09-08 18:44 UTC, josdem commented on src/main/java/com/josdem/vetlog/service/impl/PetServiceImpl.java
>          pet.setUser(user.get());
Same here:
` adopter.ifPresent(pet::setAdopter);`

2024-09-08 18:44 UTC, josdem commented on src/main/java/com/josdem/vetlog/service/impl/PetServiceImpl.java
> +            optional.ifPresent(petAdoption -> {
And here:
`optional.ifPresent(pet::setAdoption);`

2024-09-08 18:44 UTC, josdem commented on src/main/java/com/josdem/vetlog/service/impl/RecoveryServiceImpl.java
>          User user = getUserByToken(token);
Nice, good catch!

2024-09-08 18:44 UTC, josdem commented on src/main/java/com/josdem/vetlog/service/impl/UserDetailsServiceImpl.java
> +                        Arrays.asList(new SimpleGrantedAuthority(user.getRole().name()))))
I suggest using `List.of` here, the reason is that we can use an inmmutable collection here:
`List.of(new SimpleGrantedAuthority(user.getRole().name()))))`

2024-09-08 19:46 UTC, yashudhlani commented
Hi @josdem , resolved the review comments!

2024-09-08 23:57 UTC, josdem approved these changes
Thank you for doing suggested changes!

2024-09-08 23:58 UTC, josdem commented
@all-contributors please add @yashudhlani  for code

2024-09-08 23:59 UTC, merged

2024-09-09 12:43 UTC, kaminuma approved these changes