[small]feature/319
josdem/vetlog-spring-boot pull request #330
Opened 2024-09-10 15:00 UTC by josdem

- Adding mobile validation format in service and controller
- Setting mobile size as 10

2024-09-10 15:04 UTC, josdem commented on src/main/java/com/josdem/vetlog/command/UserCommand.java
In the future, we want to have this format forced by UI: (123) 456-7890
From now on, we can go with only numbers.

2024-09-10 15:52 UTC, kaminuma requested changes
HI @josdem 
I reviewed the contents of the PR, and it appears that while the CountryCode for user registration is being passed to the backend from the controller, it is not being persisted in the database.

UserBinder class add
`user.setCountryCode(userCommand.getCountryCode());`

2024-09-10 17:13 UTC, josdem commented
@all-contributors please add @kaminuma for bug

2024-09-11 10:18 UTC, kaminuma approved these changes
[LGTM]

2024-09-11 12:02 UTC, merged