Unify Thymeleaf Template Messages for Consistency
josdem/vetlog-spring-boot pull request #443
Opened 2024-11-30 12:22 UTC by iishitahere

This PR refactors the error page to ensure consistent message formatting by implementing Bootstrap alerts. It unifies the message display in the Thymeleaf template, improving readability and alignment with project standards.

2024-11-30 19:07 UTC, josdem requested changes
Hi @iishitahere, this PR needs work, I noticed we have still messages with the old format:
- https://github.com/josdem/vetlog-spring-boot/blob/d9c17d21663f83e776f9ae56b73554d091bb769f/src/main/resources/templates/home/home.html#L17L19
-  https://github.com/josdem/vetlog-spring-boot/blob/d9c17d21663f83e776f9ae56b73554d091bb769f/src/main/resources/templates/petlog/create.html#L17L20

2024-11-30 19:07 UTC, josdem commented on src/main/resources/templates/error.html
> +    <div th:data-testid="petListMessage"
`data-testid` id is normally used in E2E testing, therefore we should use a better name here, I suggest to use `th:data-testid="errorMessage"`

2024-12-01 07:00 UTC, iishitahere commented on src/main/resources/templates/error.html
> +    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
Hi @josdem,

Thank you for your feedback. I’ve worked on the changes you requested:

Reverted to the project's specific Bootstrap version.
Updated the error page according to the standardized message format.
Changed the data-testid to errorMessage, as suggested.
I believe the changes should now meet the project's requirements. Please let me know if any further adjustments are needed.

Looking forward to your feedback!

2024-12-01 08:52 UTC, kaminuma reviewed
Hi @iishitahere  @josdem
I have reviewed the code.
In my environment, when I bring the forked branch to my local environment, the styles appear broken. As a result, I was unable to verify the behavior of the centered alignment locally. However, I believe the content of the discussion above has been reflected in the code.

That said, the comment 
Revert to the project's specific Bootstrap version 

[NIT]
seems to indicate that the changes in this update were reverted. 
If this is meant to restore the original state, I feel that this comment might be unnecessary to avoid future confusion.

2024-12-01 15:37 UTC, josdem commented
> Hi @iishitahere @josdem I have reviewed the code. In my environment, when I bring the forked branch to my local environment, the styles appear broken. As a result, I was unable to verify the behavior of the centered alignment locally. However, I believe the content of the discussion above has been reflected in the code.
> 
> [NIT] That said, the comment Revert to the project's specific Bootstrap version
> 
> seems to indicate that the changes in this update were reverted. If this is meant to restore the original state, I feel that this comment might be unnecessary to avoid future confusion.

Thanks for keeping a look at it, I appreciate it!

2024-12-01 15:39 UTC, josdem commented on src/main/resources/templates/error.html
> +    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
> Hi @josdem,
> 
> Thank you for your feedback. I’ve worked on the changes you requested:
> 
> Reverted to the project's specific Bootstrap version. Updated the error page according to the standardized message format. Changed the data-testid to errorMessage, as suggested. I believe the changes should now meet the project's requirements. Please let me know if any further adjustments are needed.
> 
> Looking forward to your feedback!

Thanks, this comment needs to be addressed too: https://github.com/josdem/vetlog-spring-boot/pull/443#pullrequestreview-2471038105

2024-12-02 12:30 UTC, iishitahere commented
> Hi @iishitahere @josdem I have reviewed the code. In my environment, when I bring the forked branch to my local environment, the styles appear broken. As a result, I was unable to verify the behavior of the centered alignment locally. However, I believe the content of the discussion above has been reflected in the code.
> 
> [NIT] That said, the comment Revert to the project's specific Bootstrap version
> 
> seems to indicate that the changes in this update were reverted. If this is meant to restore the original state, I feel that this comment might be unnecessary to avoid future confusion.

Thank you for the review and feedback!

I’ll look into the styling issue and ensure the changes are verified properly.
I’ll update or remove the comment about reverting the Bootstrap version to avoid any future confusion.
Please let me know if there’s anything else you'd like me to address!

2024-12-04 13:48 UTC, kaminuma approved these changes
LGTM

2024-12-04 14:32 UTC, josdem commented
> Hi @iishitahere, this PR needs work, I noticed we have still messages with the old format:
> 
> * https://github.com/josdem/vetlog-spring-boot/blob/d9c17d21663f83e776f9ae56b73554d091bb769f/src/main/resources/templates/home/home.html#L17L19
> * https://github.com/josdem/vetlog-spring-boot/blob/d9c17d21663f83e776f9ae56b73554d091bb769f/src/main/resources/templates/petlog/create.html#L17L20

Hi, @iishitahere as I mentioned this task needs work, I can see still old message formats, please take a look at those links.

2024-12-05 16:38 UTC, closed without merging

2024-12-05 16:38 UTC, josdem commented
Closing this PR in favor of this PR: https://github.com/josdem/vetlog-spring-boot/pull/448